language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install python-pip openjdk-7-jdk
  - pip install cython six

install:
  - pip install --upgrade cython six --use-mirrors
  - make

# command to run tests
script:
  - make tests
